import type { Metadata } from "next";
import "./globals.css";

import Layout from "./components/Layout";
import { ShoppingCartProvider } from "./context/ShoppingCartContext";
import Init from "./components/Init";

export const metadata: Metadata = {
  title: "Food Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Init>
          <ShoppingCartProvider>
            <Layout>{children}</Layout>
          </ShoppingCartProvider>
        </Init>
      </body>
    </html>
  );
}
